# Generated by Django 4.1.1 on 2022-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campaign',
            field=models.IntegerField(default=1, verbose_name='Campaña'),
        ),
    ]
