# Generated by Django 4.0.8 on 2022-10-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_rol',
            field=models.IntegerField(default=1),
        ),
    ]
