# Generated by Django 4.0.8 on 2022-10-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basses', '0003_baseenviargesucs_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseenviargesucs',
            name='fecha_solucion',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 11, 41, 38, 187781)),
        ),
    ]
