# Generated by Django 4.0.8 on 2022-10-24 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basses', '0004_baseenviargesucs_fecha_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseenviargtc',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseenviargesucs',
            name='fecha_solucion',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 17, 13, 35, 658249)),
        ),
    ]
